config/routes.rb
Rails.application.routes.draw do
  
  devise_for :usuarios
  resources :facturas
  resources :clientes

  devise_scope :usuario do
   get "signup", to: "devise/registrations#new", as: :signup
   get "login", to: "devise/sessions#new", as: :login
   get "logout", to: "devise/sessions#destroy", as: :logout
end
  
  authenticated :usuario do
    root to:'facturas#index'
  end

  unauthenticated :usuario do
    get "/" => "pages#home"    
  end

  

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
   belongs_to :usuario

  validates :nombre, presence: true
  validates :apellidos, presence: true
  validates :nif, presence: true,
            uniqueness: true,
            :valid_spanish_vat => true


  #Devuelve el nombre completo del cliente
  def full_name
   nombre + " " + apellidos
  end
end

app/models/factura.rb
class Factura < ActiveRecord::Base
	belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :facturas, dependent: :destroy
  has_many :clientes, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nombre, presence: true
  validates :apellidos, presence: true
  validates :nif, presence: true,
  				 uniqueness: true,
  				 :valid_spanish_vat => true


  #Devuelve el nombre completo del usuario
  def full_name
  	nombre + " " + apellidos
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nif
    devise_parameter_sanitizer.for(:sign_up) << :nombre
    devise_parameter_sanitizer.for(:sign_up) << :apellidos
    devise_parameter_sanitizer.for(:sign_up) << :nombre_comercial
    devise_parameter_sanitizer.for(:sign_up) << :telefono
    devise_parameter_sanitizer.for(:sign_up) << :fax
    devise_parameter_sanitizer.for(:sign_up) << :telf_movil
    devise_parameter_sanitizer.for(:sign_up) << :web
  end

  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_usuario!

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = current_usuario.clientes
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    #@cliente = Cliente.new(cliente_params)
    @cliente = current_usuario.clientes.build(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nif, :nombre, :apellidos, :nombre_comercial, :telefono, :telf_movil, :fax, :email, :web, :descripcion, :imagen)
    end
end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_usuario!

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
  end

  # GET /facturas/new
  def new
    @factura = Factura.new
  end

  # GET /facturas/1/edit
  def edit
  end

  # POST /facturas
  # POST /facturas.json
  def create
    #@factura = Factura.new(factura_params)   #Sin usuario vinculado
    @factura = current_usuario.facturas.build(factura_params)

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'Factura was successfully created.' }
        format.json { render :show, status: :created, location: @factura }
      else
        format.html { render :new }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas/1
  # PATCH/PUT /facturas/1.json
  def update
    respond_to do |format|
      if @factura.update(factura_params)
        format.html { redirect_to @factura, notice: 'Factura was successfully updated.' }
        format.json { render :show, status: :ok, location: @factura }
      else
        format.html { render :edit }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura.destroy
    respond_to do |format|
      format.html { redirect_to facturas_url, notice: 'Factura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura
      @factura = Factura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_params
      params.require(:factura).permit(:fecha_alta, :serie_factura, :numero_factura, :comentario, :usuario_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
          when 'notice' then "alert alert-info"
          when 'success' then "alert alert-success"
          when 'error' then "alert alert-danger"
          when 'alert' then "alert alert-warning"
        end
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nif %>
    <%= f.input :nombre %>
    <%= f.input :apellidos %>
    <%= f.input :nombre_comercial %>
    <%= f.input :telefono %>
    <%= f.input :telf_movil %>
    <%= f.input :fax %>
    <%= f.input :email %>
    <%= f.input :web %>
    <%= f.input :descripcion %>
    <%= f.input :imagen %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nif</th>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Nombre comercial</th>
      <th>Telefono</th>
      <th>Telf movil</th>
      <th>Fax</th>
      <th>Email</th>
      <th>Web</th>
      <th>Descripcion</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_usuario.clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nif %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellidos %></td>
        <td><%= cliente.nombre_comercial %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.telf_movil %></td>
        <td><%= cliente.fax %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.web %></td>
        <td><%= cliente.descripcion %></td>
        <td><%= cliente.imagen %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nif:</strong>
  <%= @cliente.nif %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @cliente.apellidos %>
</p>

<p>
  <strong>Nombre comercial:</strong>
  <%= @cliente.nombre_comercial %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>Telf movil:</strong>
  <%= @cliente.telf_movil %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @cliente.fax %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Web:</strong>
  <%= @cliente.web %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @cliente.descripcion %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @cliente.imagen %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/facturas/_form.html.erb
<%= simple_form_for(@factura, html:{class: "form-horizontal"}) do |f| %>
  <% if @factura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factura.errors.count, "error") %> prohibited this factura from being saved:</h2>

      <ul>
      <% @factura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.input :fecha_alta %>

  <%= f.input :serie_factura %>

  <%= f.input :numero_factura %>

  <%= f.input :comentario %>


   
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/facturas/edit.html.erb
<h1>Editing factura</h1>

<%= render 'form' %>

<%= link_to 'Show', @factura %> |
<%= link_to 'Back', facturas_path %>

app/views/facturas/index.html.erb
<div class="page-header">
  <h1>Facturas</h1>
</div>

<table>
  <thead>
    <tr>
      <th>Fecha factura |</th>
      <th> Serie factura |</th>
      <th> Numero factura |</th>
      <th> Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_usuario.facturas.each do |factura| %>
      <tr>
        <td><%= factura.fecha_alta %></td>
        <td><%= factura.serie_factura %></td>
        <td><%= factura.numero_factura %></td>
        <td><%= factura.comentario %></td>
        <td><%= link_to 'Show', factura %></td>
        <td><%= link_to 'Edit', edit_factura_path(factura) %></td>
        <td><%= link_to 'Destroy', factura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Factura', new_factura_path %>

app/views/facturas/new.html.erb
<h1>New factura</h1>

<%= render 'form' %>

<%= link_to 'Back', facturas_path %>

app/views/facturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Nombre: </b>
	<%=  @factura.usuario.nombre %>
</p>
<p>
  <strong>Fecha alta:</strong>
  <%= @factura.fecha_alta %>
</p>

<p>
  <strong>Serie factura:</strong>
  <%= @factura.serie_factura %>
</p>

<p>
  <strong>Numero factura:</strong>
  <%= @factura.numero_factura %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @factura.comentario %>
</p>

<%= link_to 'Edit', edit_factura_path(@factura) %> |
<%= link_to 'Back', facturas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gefactura</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if usuario_signed_in?%>
  	<div class="navbar navbar-fixed-top navbar-default" role="navigation">
  		<div class="navbar-inner">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Gefactura</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "Facturas", facturas_path %></li>
                <li><%= link_to "Clientes", clientes_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
               		 <% if usuario_signed_in? %>
  			    		<li> <%= link_to current_usuario.full_name, edit_usuario_registration_path %> </li>
  			    		<li> <%= link_to "Cerrar Sesión", logout_path %> </li>
  			    	<% else %>
  			    		<li> <%= link_to "Regístrate", signup_path %> </li>
  			    		<li> <%= link_to "Iniciar Sesión", login_path %> </li>
  			    			
  		    		<% end %>
              </ul>
            </div><!--/.nav-collapse -->
          </div><!--/.container-fluid -->
          </div>
        </div>
      <% end %>
      <div class="container">		
        <% flash.each do |type, message| %>
          <div class="<%= flash_class(type) %>">
            <button class="close" data-dismiss="alert">x</button>
            <%= message %>
          </div>
        <% end %>
      	
    		<%= yield %>
    	</div>
	
	

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
	<head>
		<meta charset="utf-8">
		<title>Slick Login</title>
		<meta name="description" content="slick Login">
		<meta name="author" content="Webdesigntuts+">
		<link rel="stylesheet" type="text/css" href="style_home.css" />
		<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
		<script src="http://www.modernizr.com/downloads/modernizr-latest.js"></script>
		<script type="text/javascript" src="placeholder.js"></script>
		</head>
	<body>
		<form id="slick-login">
			<label for="username">username</label><input type="text" name="username" class="placeholder" placeholder="me@tutsplus.com">
			<label for="password">password</label><input type="password" name="password" class="placeholder" placeholder="password">
			<input type="submit" value="Log In">
		</form>
	</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="UTF-8">

  <title>Gefisco - Gefactura</title>

    <style>


body{
	margin: 0;
	padding: 0;
	background: #fff;

	color: #fff;
	font-family: Arial;
	font-size: 12px;
}

.body{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background-image: url(/assets/fondo.jpg);
	background-size: cover;
	-webkit-filter: blur(5px);
	z-index: 0;
}

.grad{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
	z-index: 1;
	opacity: 0.7;
}

.header{
	position: absolute;
	top: calc(50% - 35px);
	left: calc(50% - 255px);
	z-index: 2;
}

.header div{
	float: left;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 35px;
	font-weight: 200;
}

.header div span{
	color: #5379fa !important;
}

.login{
	position: absolute;
	top: calc(50% - 75px);
	left: calc(50% - 50px);
	height: 150px;
	width: 350px;
	padding: 10px;
	z-index: 2;
}

.login input[type=text]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
}

.login input[type=password]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
	margin-top: 10px;
}

.login input[type=submit]{
	width: 260px;
	height: 35px;
	background: #fff;
	border: 1px solid #fff;
	cursor: pointer;
	border-radius: 2px;
	color: #a18d6c;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 6px;
	margin-top: 10px;
}

.login input[type=submit]:hover{
	opacity: 0.8;
}

.login input[type=submit]:active{
	opacity: 0.6;
}

.login input[type=text]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=password]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=submit]:focus{
	outline: none;
}

::-webkit-input-placeholder{
   color: rgba(255,255,255,0.6);
}

::-moz-input-placeholder{
   color: rgba(255,255,255,0.6);
}
</style>

    <script src="js/prefixfree.min.js"></script>

</head>

<body>

  <div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<div>Ge<span>factura</span></div>
		</div>
		<br>
		<div class="login">
		<%= form_for(:usuario, :url => session_path(:usuario)) do |f| %>
			<%= f.text_field :email, :placeholder => "Email" %>
			<%= f.password_field :password, :placeholder => "Password" %>
			<%= f.submit 'Sign in' %>
			<br>
			<%= f.check_box :remember_me %>
			<%= f.label :remember_me %>
			<br>
			<%= link_to "Forgot your password?", new_password_path(:usuario) %>
			<%= link_to "Register", signup_path %>
		<% end %>
				
		</div>

  <script body.src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>


</body>

</html>